apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: ddueruem
  POSTGRES_USER: ddueruem
  POSTGRES_PASSWORD: ddueruem
  postgre-url: postgres